# Generated by Django 5.1.4 on 2024-12-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='youtube_link',
            new_name='external_link',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='youtube_title',
            new_name='external_title',
        ),
    ]
