# Generated by Django 5.1.4 on 2024-12-31 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_generator', '0004_remove_blogpost_title_blogpost_external_link_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
